@host = http://localhost:3000


### POSTS

GET {{host}}/posts


###
GET {{host}}/posts/12


###
POST {{host}}/posts/new
Content-Type: application/json

{
    "Nombre": "Sara",
    "Apellidos": "Garrofé"
}


###
PUT {{host}}/posts/33


###
DELETE {{host}}/posts/postId 



### AUTORES 


GET {{host}}/autores


###
GET {{host}}/autores/autorId

###
GET {{host}}/autores/autorId/posts

### 
POST {{host}}/autores/new


###
PUT {{host}}/autores/edit

### 
DELETE {{host}}/autores/autorId


