@host = http://localhost:3000


### POSTS

GET {{host}}/posts


###
GET {{host}}/posts/7


###
POST {{host}}/posts/new
Content-Type: application/json

{
    "titulo": "titulo de la noticia",
    "descripcion": "descripcion chulisima",
    "fecha_creacion": "2023-05-17 10:00:00",
    "categoria": "deportes",
    "autores_id": 4
}


###
PUT {{host}}/posts/8
Content-Type: application/json

{
    "titulo": "El cámara Miguel Ángel de la Fuente gana el Premio Cirilo Rodríguez de periodismo",
    "descripcion": "Óscar Mijallo y María Senovilla resultan finalistas. Y el colaborador de EL PAÍS Aurelio Martín ha recibido el galardón de honor",
    "fecha_creacion": "2023-05-22 09:20:00",
    "categoria": "sociedad",
    "autores_id": 4
}



###
DELETE {{host}}/posts/9 



### AUTORES 


GET {{host}}/autores

###
GET {{host}}/autores/posts/2

###
GET {{host}}/autores/11



### 
POST {{host}}/autores/new
Content-Type: application/json

{
    "nombrsse": "Victoria",
    "apellidos": "Guevara",
    "email": "victoriaguevara@gmail.com",
    "imagen": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.livecareer.es%2Fcurriculum-vitae%2Ffoto-curriculum&psig=AOvVaw2pb5RkG1WetWdsHOVfsO_5&ust=1684600874080000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCJj2sLfpgf8CFQAAAAAdAAAAABAU"
}


###
PUT {{host}}/autores/11
Content-Type: application/json

{
    "nombre": "Victor",
    "apellidos": "Guevara",
    "email": "victoriaguevara@gmail.com",
    "imagen": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.livecareer.es%2Fcurriculum-vitae%2Ffoto-curriculum&psig=AOvVaw2pb5RkG1WetWdsHOVfsO_5&ust=1684600874080000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCJj2sLfpgf8CFQAAAAAdAAAAABAU"
}

### 
DELETE {{host}}/autores/11


